# Generated by Django 2.1.4 on 2018-12-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockkdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfComapanies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=10, unique=True)),
                ('security_id', models.CharField(max_length=30, unique=True)),
                ('security_name', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
