# Generated by Django 2.1.4 on 2018-12-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockkdata', '0003_auto_20181217_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofcompanies',
            name='url',
            field=models.URLField(default=None, verbose_name='BSE company url'),
        ),
    ]
