# Generated by Django 2.1.4 on 2018-12-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockkdata', '0004_listofcompanies_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofcompanies',
            name='company_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
