# Generated by Django 2.1.4 on 2018-12-26 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockkdata', '0007_auto_20181217_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='agm_egm',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stockkdata.ListOfCompanies'),
        ),
        migrations.AddField(
            model_name='boardmeeting',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stockkdata.ListOfCompanies'),
        ),
        migrations.AddField(
            model_name='companyupdate',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stockkdata.ListOfCompanies'),
        ),
        migrations.AddField(
            model_name='corpaction',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stockkdata.ListOfCompanies'),
        ),
        migrations.AddField(
            model_name='newlisting',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stockkdata.ListOfCompanies'),
        ),
        migrations.AddField(
            model_name='result',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stockkdata.ListOfCompanies'),
        ),
        migrations.AddField(
            model_name='sast',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stockkdata.ListOfCompanies'),
        ),
        migrations.AlterField(
            model_name='agm_egm',
            name='link_to_pdf',
            field=models.URLField(default=None, verbose_name='actual_pdf_url'),
        ),
        migrations.AlterField(
            model_name='boardmeeting',
            name='link_to_pdf',
            field=models.URLField(default=None, verbose_name='actual_pdf_url'),
        ),
        migrations.AlterField(
            model_name='companyupdate',
            name='link_to_pdf',
            field=models.URLField(default=None, verbose_name='actual_pdf_url'),
        ),
        migrations.AlterField(
            model_name='corpaction',
            name='link_to_pdf',
            field=models.URLField(default=None, verbose_name='actual_pdf_url'),
        ),
        migrations.AlterField(
            model_name='newlisting',
            name='link_to_pdf',
            field=models.URLField(default=None, verbose_name='actual_pdf_url'),
        ),
        migrations.AlterField(
            model_name='result',
            name='link_to_pdf',
            field=models.URLField(default=None, verbose_name='actual_pdf_url'),
        ),
        migrations.AlterField(
            model_name='sast',
            name='link_to_pdf',
            field=models.URLField(default=None, verbose_name='actual_pdf_url'),
        ),
    ]
