# Generated by Django 2.1.4 on 2018-12-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CTR', 'CUSTOMER'), ('ADM', 'ADMIN')], default='CTR', max_length=3),
        ),
    ]
