# Generated by Django 2.1.4 on 2018-12-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AGM_EGM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
                ('link_to_pdf', models.URLField(verbose_name='actual_pdf_url')),
            ],
        ),
        migrations.CreateModel(
            name='BoardMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
                ('link_to_pdf', models.URLField(verbose_name='actual_pdf_url')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
                ('link_to_pdf', models.URLField(verbose_name='actual_pdf_url')),
            ],
        ),
        migrations.CreateModel(
            name='CorpAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
                ('link_to_pdf', models.URLField(verbose_name='actual_pdf_url')),
            ],
        ),
        migrations.CreateModel(
            name='NewListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
                ('link_to_pdf', models.URLField(verbose_name='actual_pdf_url')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
                ('link_to_pdf', models.URLField(verbose_name='actual_pdf_url')),
            ],
        ),
        migrations.CreateModel(
            name='SAST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
                ('link_to_pdf', models.URLField(verbose_name='actual_pdf_url')),
            ],
        ),
    ]
