# Generated by Django 2.1.4 on 2018-12-17 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockkdata', '0002_listofcomapanies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListOfComapanies',
            new_name='ListOfCompanies',
        ),
    ]
