# Generated by Django 2.1.4 on 2018-12-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockkdata', '0008_auto_20181226_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agm_egm',
            name='link_to_pdf',
            field=models.URLField(verbose_name='actual_pdf_url'),
        ),
        migrations.AlterField(
            model_name='boardmeeting',
            name='link_to_pdf',
            field=models.URLField(verbose_name='actual_pdf_url'),
        ),
        migrations.AlterField(
            model_name='companyupdate',
            name='link_to_pdf',
            field=models.URLField(verbose_name='actual_pdf_url'),
        ),
        migrations.AlterField(
            model_name='corpaction',
            name='link_to_pdf',
            field=models.URLField(verbose_name='actual_pdf_url'),
        ),
        migrations.AlterField(
            model_name='newlisting',
            name='link_to_pdf',
            field=models.URLField(verbose_name='actual_pdf_url'),
        ),
        migrations.AlterField(
            model_name='result',
            name='link_to_pdf',
            field=models.URLField(verbose_name='actual_pdf_url'),
        ),
        migrations.AlterField(
            model_name='sast',
            name='link_to_pdf',
            field=models.URLField(verbose_name='actual_pdf_url'),
        ),
    ]
