# Generated by Django 2.1.4 on 2018-12-26 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockkdata', '0009_auto_20181226_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Random',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
                ('link_to_pdf', models.URLField(verbose_name='actual_pdf_url')),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stockkdata.ListOfCompanies')),
            ],
        ),
    ]
