# Generated by Django 2.1.4 on 2018-12-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockkdata', '0010_random'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agm_egm',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='boardmeeting',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='companyupdate',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='corpaction',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='newlisting',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='random',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='result',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sast',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
