# Generated by Django 2.1.4 on 2019-01-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockkdata', '0011_auto_20181228_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
    ]
