# Generated by Django 2.1.4 on 2018-12-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0002_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_number',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
    ]
